permalink: /:year:month:day/:title


# variables
name: 'MoongJong93'
description: '웹 개발에 관한 이야기, Node.js와 Vue.js를 중점적으로 사용합니다'

permalink: /:categories/:title/ 

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  
paginate: 5
paginate_path: "/:num"