permalink: /:year:month:day/:title
permalink: /:categories/:title/ 


# variables
name: '종민'
description: '개발로그 및 일상'

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  
paginate: 10
paginate_path: "/:num"