permalink: /:year:month:day/:title

# variables
name: Your Site Name
description: Your description here
google_verification: null


permalink: /:categories/:title/ 

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true