permalink: /:year:month:day/:title

# variables
name: Moonjong93 blog
description: 웹 개발을 하고 있습니다 Node.js, vue.js 등
google_verification: null

permalink: /:categories/:title/ 

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true